spring.application.name=album-copa

#banco de dados conectado com java criado na memoria
spring.datasource.url=jdbc:h2:mem:albumdb
#use o drive oficial do H2
spring.datasource.driver-class-name=org.h2.Driver
#
spring.datasource.username=sa
spring.datasource.password=

#Cria e atualiza tabelas automaticamente
#jpa transforma tabela em banco
spring.jpa.hibernate.ddl-auto=update

# Habilita painel do H2
spring.h2.console.enabled=true